version: '2.1'
services:
  backend:
    build: .
    ports:
      - 8080:80
    environment:
      - DB_HOST=postgres
      - DB_USER=dbuser
      - DB_PASSWORD=abc123
      - DB_NAME=work_timer_db
    links:
      - postgres
    restart: always
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
      image: postgres:11
      command: postgres -c 'log_statement=all'
      ports:
        - "5432:5432"
      environment:
        - POSTGRES_DB=work_timer_db
        - POSTGRES_USER=dbuser
        - POSTGRES_PASSWORD=abc123
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -h localhost -p 5432 -U dbuser -d work_timer_db"]
        interval: 5s
        timeout: 10s
        retries: 10
